### ISSUE TITLE
Node-RED is installed at /usr/bin/node-red but the service uses /usr/local/bin/node-red

### ISSUE THREAD

**Issue by phillipsnick** [robertdebock/ansible-role-node_red#1]
## Describe the bug

I'm installing on a Raspberry Pi running Debian GNU/Linux 11 (bullseye)

Using this role Node-RED is installed at /usr/bin/node-red but the service uses /usr/local/bin/node-red

I tried to override the default value here with little success https://github.com/robertdebock/ansible-role-node_red/blob/master/vars/main.yml#L14

## Playbook

```yaml
- hosts: all
  roles:
    - role: geerlingguy.nodejs
      become: true
    - role: robertdebock.node_red
      become: true
      node_red_user_name: "{{ ansible_user_id }}"
      node_red_group_name: "{{ ansible_user_id }}"
      vars:
        node_red_start_command: /usr/bin/node-red
```

## Output

cat of /etc/systemd/system/nodered.service

```
#
# Ansible managed
#
[Unit]
Description=Node RED

[Service]
WorkingDirectory=/opt/node_red
User=nick
Group=nick
ExecStart=/usr/local/bin/node-red

[Install]
WantedBy=multi-user.target
```

## Environment

- Control node OS: macOS 13.4.1
- Control node Ansible version: 2.12.2
- Managed node OS: Debian GNU/Linux 11 (bullseye)
